name: Continuous Integration Checks

# All branches
on: push

jobs:
  build:

    name: Unit tests and code style checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run CI
        run: |
          pip install -r requirements/testing.txt
          tox
